# Generated by Django 4.2.5 on 2023-09-11 06:12

import django.core.validators
from django.db import migrations, models
from django.core.validators import RegexValidator

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images')),
                ('designation', models.CharField(max_length=100)),
                ('emai_adress', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(
                    max_length=13, blank=True, 
                    validators=[RegexValidator(r'^(\+\d{1,2}|\d{1,2})\s?\d{3}\)?[\d\- ]{0,10}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
